### ISSUE TITLE
C interface: library does not build anymore with swi-prolog 9.3.8

### ISSUE THREAD

**Issue by quibo** [SWI-Prolog/swipl-devel#1415]
I have a library written in C that used to build perfectly well.  Since an upgrade of swi-prolog to 9.3.8 (on gentoo), I have errors on any predicate with arity > 0.

--or it's me... I am no master in this; moreover, I have not tried to downgrade my system in order to double check, because, well...

This is a minimal example (`bug-register.c`):
```
#include <SWI-Prolog.h>

foreign_t arity_0(void) {
  PL_succeed;
}

foreign_t arity_1(term_t t) {
  return PL_unify_int64(t, 0);
}

install_t install(void) {
  PL_register_foreign("arity0", 0, arity_0, 0);
  PL_register_foreign("arity1", 1, arity_1, 0);
}
```

I compile with:
```
swipl-ld -shared -o bug-register.so bug-register.c
```

And I get errors like this, for any predicate with arity > 0 (error message slightly shortened and long lines wrapped):
```
bug-register.c: In function ‘install’:
bug-register.c:13:36: error: passing argument 3 of ‘PL_register_foreign’ from incompatible pointer type
               [-Wincompatible-pointer-types]
   13 |   PL_register_foreign("arity1", 1, arity_1, 0);
      |                                    ^~~~~~~
      |                                    |
      |                                    foreign_t (*)(term_t) {aka long unsigned int (*)(long unsigned int)}
In file included from bug-register.c:1:
/usr/lib/swipl/include/SWI-Prolog.h:370:59: note: expected ‘pl_function_t’ {aka ‘long unsigned int (*)(void)’}
                but argument is of type ‘foreign_t (*)(term_t)’ {aka ‘long unsigned int (*)(long unsigned int)’}
  370 |                                             pl_function_t func,
      |                                             ~~~~~~~~~~~~~~^~~~
```

**Comment by JanWielemaker** [comment]
The actual change is that recent C compiler got more picky.    One way around is to upgrade to a more recent version of SWI-Prolog.   I think you can also get around this using an explicit cast.

     PL_register_foreign("arity1", 1, (void*)arity_1, 0);

**Comment by quibo** [comment]
The cast worked like a breeze.  Thanks!

gentoo is only up to 9.3.8, and I prefer waiting rather than building swi-prolog in my home...

**Comment by quibo** [comment]
Well, yes, i did HUP gentoo.
