### ISSUE TITLE
cross compilation terminates with failure to execute archive4pl

### ISSUE THREAD

**Issue by Biswa96** [SWI-Prolog/swipl-devel#1365]
* build log https://github.com/termux/termux-packages/issues/24399
* build script https://github.com/termux/termux-packages/tree/master/packages/swi-prolog

I can provide further information if required.

**Comment by JanWielemaker** [comment]
I'm running around in circles, but so far failed to find the actual log.    Can you add the link?

**Comment by Biswa96** [comment]
Please click on the "Show log" line in the issue.

**Comment by JanWielemaker** [comment]
As, I was looking for a link ...    It is not entirely clear to me what is going on.    It seems related to QLF installation.    That is still broken in 9.2.23, explaining part of the error.    It is not clear what happens with libarchive though.   Early it claims it is not present, later it configures it anyway but then it seems it cannot load the .so file.    Similar with Python and Java.  A number of the issues are already fixed in 9.3.24 and more in the current GIT version.    If you cannot build from the git version, it might be best to wait for 9.3.25.    Then we can see what remains.    You can most likely get it to build using `-DINSTALL_QLF=OFF`, but that is a pity as using the .qlf libraries is particularly useful on slow mobile devices.

**Comment by Biswa96** [comment]
Thanks for the hint. I have tried the current master branch of this repository and it builds without any error. Some directories are missing after installing it, e.g. PREFIX/lib/swipl/doc/packages/examples/, PREFIX/lib/swipl/lib/arm64-android/, PREFIX/lib/swipl/library/ext/. would that cause any issue?

**Comment by JanWielemaker** [comment]
Sounds dubious.   What happens if you run `?- check_installation.` in the final system?

**Comment by robertkirkman** [comment]
@Biswa96 I think that I have found ways of basically fixing or working around all observable errors during the cross-compilation,

if you would like to, you can review my PR to check it.

**Comment by robertkirkman** [comment]
> You can most likely get it to build using `-DINSTALL_QLF=OFF`, but that is a pity as using the `.qlf` libraries is particularly useful on slow mobile devices.

Unfortunately, I was not able to fix `-DINSTALL_QLF=ON`, but the current `swi-prolog` we package at version 9.3.22 also does not contain most of the `.qlf` files we are discussing, so I assume that it is fine not to include them if they are not building correctly.

**Comment by robertkirkman** [comment]
> Sounds dubious. What happens if you run `?- check_installation.` in the final system?

Both our current `swi-prolog` 9.3.22, and the bump to version 9.3.30 that I just opened, have this output from that (no change in "issues" between older and newer):

```
1 ?- check_installation.
% Checking your SWI-Prolog kit for common issues ...
% 
% Version: ............. 9.3.30
% Address bits: ........ 64
% Architecture: ........ arm64-android
% Installed at: ........ /data/data/com.termux/files/usr/lib/swipl
% Cores: ............... 8
% 
% Checking gmp ................................. ok
% Loading library(archive) ..................... ok
%   Supported filters: bzip2, compress, gzip, grzip, lrzip, lzip, lzma, lzop, none, rpm, uu, xz
%   Supported formats: 7zip, ar, cab, cpio, empty, gnutar, iso9660, lha, mtree, rar, raw, tar, xar, zip
% Loading library(cgi) ......................... ok
% Loading library(crypt) ....................... ok
Warning: library(bdb) .......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/bdb.html
% Loading library(double_metaphone) ............ ok
Warning: library(editline) ..................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/editline.html
% Loading library(filesex) ..................... ok
% Loading library(http/http_stream) ............ ok
% Loading library(http/json) ................... ok
% Loading library(http/jquery) ................. ok
%   jQuery from /data/data/com.termux/files/usr/lib/swipl/library/http/web/js/jquery-3.6.0.min.js
% Loading library(isub) ........................ ok
% Loading library(janus) ....................... ok
% Interactive session; added `.` to Python `sys.path`
%   Python version 3.12.11 (main, Aug 27 2025, 21:27:47) [Clang 19.0.1 (https://android.googlesource.com/toolchain/llvm-project 97a699bf4
% Loading library(jpl) ......................... FAILED
Warning: Cannot load required shared library
Warning: See http://www.swi-prolog.org/build/issues/jpl.html
% Loading library(memfile) ..................... ok
Warning: library(odbc) ......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/odbc.html
Warning: library(pce) .......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/xpce.html
% Loading library(pcre) ........................ ok
% Loading library(pdt_console) ................. ok
% Loading library(porter_stem) ................. ok
% Loading library(process) ..................... ok
% Loading library(protobufs) ................... ok
% Loading library(readutil) .................... ok
% Loading library(rlimit) ...................... ok
% Loading library(semweb/rdf_db) ............... ok
% Loading library(semweb/rdf_ntriples) ......... ok
% Loading library(semweb/turtle) ............... ok
% Loading library(sgml) ........................ ok
% Loading library(sha) ......................... ok
% Loading library(snowball) .................... ok
% Loading library(socket) ...................... ok
% Loading library(ssl) ......................... ok
% Loading library(sweep_link) .................. ok
%   GNU-Emacs plugin loads
%     L /data/data/com.termux/files/usr/lib/libswipl.so
%     M /data/data/com.termux/files/usr/lib/swipl/lib/arm64-android/sweep-module.so
% Loading library(crypto) ...................... ok
% Loading library(syslog) ...................... ok
% Loading library(table) ....................... ok
% Loading library(time) ........................ ok
% Loading library(unicode) ..................... ok
% Loading library(uri) ......................... ok
% Loading library(uuid) ........................ ok
% Loading library(yaml) ........................ ok
% Loading library(zlib) ........................ ok
Warning: Found 5 issues.
true.
```

If you know that any of these are especially bad, you can let us know and I can try to fix them, but I am not sure if anyone in Termux currently needs those features which are marked as "issues" here.

**Comment by JanWielemaker** [comment]
I think the check_installation/0 is pretty much ok.    Having libedit to work might be interesting as it brings command completion and history.    Will be hard if libedit is not available of course.    

If we are really ambitious we could try to support xpce.   With its move to SDL+Cairo+Pango, I think it should in theory run on Android.

Getting QLF build to work should be possible, but might be complicated.  The big advantage is that it cuts the library load time 10 fold or more.    That is notably nice for big libraries such as library(clpfd).     The "native friend" should be able to do that for any library that is not affected by conditional compilation that differs between the host and target platforms.

**Comment by robertkirkman** [comment]
Thank you for explaining,

Historically, Termux has used `readline` to provide a command history implementation to `swi-prolog`, but I was wondering about why all log messages about `readline` had disappeared from `swi-prolog` in Termux in the newer version.

I can see now that by default, it appears that `readline` is in the process of being, or has been, turned off in `swi-prolog`, as a result of these two commits one after the other:

1. On July 4th 2025, `EPILOG` option was created and set to disable `readline` if it is enabled https://github.com/SWI-Prolog/swipl-devel/commit/e347541bd49c5fd3a47fa79d77abd6c120b5882e#diff-b52089e6ab3ef441de3c021dfb0c92539c2d8c00de287404399880a1b6423b6cR85
2. On July 23rd 2025, the `EPILOG` option was enabled by default, effectively disabling `readline` https://github.com/SWI-Prolog/swipl-devel/commit/0f789c9cd30c6fc089c006b05ef3764126c7af8f

`libedit` _is_ available as a package in Termux, but the reason why `libedit` is not active for me in `swi-prolog` yet is most likely because it has not yet been added to our `swi-prolog` package dependencies and verified to enable the functionality as a replacement for `readline`.

I can see that this means I need to reevaluate the dependencies of `swi-prolog`, and I will probably try reconfiguring the other dependencies we are discussing as well, to see if I can get them to activate more appropriately.

**Comment by JanWielemaker** [comment]
> Historically, Termux has used `readline` to provide a command history implementation to `swi-prolog`, but I was wondering about why all log messages about `readline` had disappeared from `swi-prolog` in Termux in the newer version.

Yes.   Maintaining two commandline editor interfaces was a bit too much and libedit fits SWI-Prolog better for license reasons as well as the ability to have multiple instances of libedit in the same process.    As libedit is available, just changing the dependency should be enough.

**Comment by robertkirkman** [comment]
After making a lot of changes to the Termux `swi-prolog` package, I have managed to get all of the tests of `check_installation.` to pass except for two:

```
~ $ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 9.3.30)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org

?- check_installation.
% Checking your SWI-Prolog kit for common issues ...
% 
% Version: ............. 9.3.30
% Address bits: ........ 64
% Architecture: ........ arm64-android
% Installed at: ........ /data/data/com.termux/files/usr/lib/swipl
% Cores: ............... 8
% 
% Checking gmp ................................. ok
% Loading library(archive) ..................... ok
%   Supported filters: bzip2, compress, gzip, grzip, lrzip, lzip, lzma, lzop, none, rpm, uu, xz
%   Supported formats: 7zip, ar, cab, cpio, empty, gnutar, iso9660, lha, mtree, rar, raw, tar, xar, zip
% Loading library(cgi) ......................... ok
% Loading library(crypt) ....................... ok
% Loading library(bdb) ......................... ok
% Loading library(double_metaphone) ............ ok
% Loading library(editline) .................... ok
% Loading library(filesex) ..................... ok
% Loading library(http/http_stream) ............ ok
% Loading library(http/json) ................... ok
% Loading library(http/jquery) ................. ok
%   jQuery from /data/data/com.termux/files/usr/lib/swipl/library/http/web/js/jquery-3.6.0.min.js
% Loading library(isub) ........................ ok
% Loading library(janus) ....................... ok
% Interactive session; added `.` to Python `sys.path`
%   Python version 3.12.11 (main, Aug 27 2025, 21:27:47) [Clang 19.0.1 (https://android.googlesource.com/toolchain/llvm-project 97a699bf4
Warning: library(jpl) .......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/jpl.html
% Loading library(memfile) ..................... ok
% Loading library(odbc) ........................ ok
Warning: library(pce) .......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/xpce.html
% Loading library(pcre) ........................ ok
% Loading library(pdt_console) ................. ok
% Loading library(porter_stem) ................. ok
% Loading library(process) ..................... ok
% Loading library(protobufs) ................... ok
% Loading library(readutil) .................... ok
% Loading library(rlimit) ...................... ok
% Loading library(semweb/rdf_db) ............... ok
% Loading library(semweb/rdf_ntriples) ......... ok
% Loading library(semweb/turtle) ............... ok
% Loading library(sgml) ........................ ok
% Loading library(sha) ......................... ok
% Loading library(snowball) .................... ok
% Loading library(socket) ...................... ok
% Loading library(ssl) ......................... ok
% Loading library(sweep_link) .................. ok
%   GNU-Emacs plugin loads
%     L /data/data/com.termux/files/usr/lib/libswipl.so
%     M /data/data/com.termux/files/usr/lib/swipl/lib/arm64-android/sweep-module.so
% Loading library(crypto) ...................... ok
% Loading library(syslog) ...................... ok
% Loading library(table) ....................... ok
% Loading library(time) ........................ ok
% Loading library(unicode) ..................... ok
% Loading library(uri) ......................... ok
% Loading library(uuid) ........................ ok
% Loading library(yaml) ........................ ok
% Loading library(zlib) ........................ ok
Warning: Found 2 issues.
true.

?- 
```

Those remaining two are a bit more difficult to set up correctly for us than the others, so I hope this improvement is sufficient.

I have also manually confirmed that the command history support with `libedit` instead of `readline` is now working.

**Comment by robertkirkman** [comment]
I have also collected more information about the QLF error to post, which you do not have to spend a lot of your time trying to fix like I have, I am just posting it in case you might have a very good idea already of what might be wrong, since unfortunately, I am completely confused by this, and I do not understand Prolog very well, so that might be part of why I do not understand what is going wrong with the QLF files.

I have managed to count the total number of `.qlf` files that are not being correctly generated, and I have also managed to create a workaround that allows me to bypass the error and install the rest of the `.qlf` files successfully despite that.

```diff
--- a/cmake/InstallSource.cmake
+++ b/cmake/InstallSource.cmake
@@ -185,6 +185,12 @@ set(noqlf_pattern
     "home/library/ext/ltx2htm/sty_.*[.]pl")
 
 set(noqlf_file
+    packages/chr//chr.pl
+    packages/chr//chr_translate.pl
+    packages/chr//chr_translate_bootstrap1.pl
+    packages/chr//chr_translate_bootstrap2.pl
+    packages/chr//guard_entailment.pl
+    packages/http/jquery.pl
     home/library/tabling.pl
     home/library/prolog_qlfmake.pl
     home/library/win_menu.pl
```

the total number of `.qlf` files that are failing to generate is 6, but unfortunately, I noticed that some of them, like `chr_translate.qlf`, are much larger than most of the other `.qlf` files, which suggests to me that they are probably the most important and that a sigificant benefit of the `.qlf` files might be lost without them.

```
[1078/1078] QLF compile library
[39/40] Install the project...
-- Install configuration: "Release"
CMake Error at packages/chr/cmake_install.cmake:92 (file):
  file INSTALL cannot find
  "/home/builder/.termux-build/swi-prolog/build/packages/chr//chr.qlf": No
  such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:63 (include)


FAILED: CMakeFiles/install.util 
cd /home/builder/.termux-build/swi-prolog/build && /home/builder/.termux-build/_cache/cmake-4.1.1/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

the "native friend" folder (in Termux, we call it "hostbuild" in the general case for other software)

All `.qlf` files were generated, including all in both the `packages/chr` folder and the `home/library` folder.
```
builder@3d3d29281e32:~/.termux-build/swi-prolog$ ls host-build/packages/chr
chr.pl   chr_translate_bootstrap1.pl  chr_translate.pl   CMakeFiles           guard_entailment.pl
chr.qlf  chr_translate_bootstrap2.pl  chr_translate.qlf  cmake_install.cmake  guard_entailment.qlf
builder@3d3d29281e32:~/.termux-build/swi-prolog$ ls host-build/home/library/ | head
aggregate.pl
aggregate.qlf
ansi_term.pl
ansi_term.qlf
apply_macros.pl
apply_macros.qlf
apply.pl
apply.qlf
arithmetic.pl
arithmetic.qlf
builder@3d3d29281e32:~/.termux-build/swi-prolog$ 
```

the cross-compilation build folder, after the error has occurred.

Some `.qlf` files were generated, but not any that should be there in the `packages/chr` folder.
```
builder@3d3d29281e32:~/.termux-build/swi-prolog$ ls build/packages/chr/
chr.pl                       chr_translate_bootstrap2.pl  CMakeFiles           guard_entailment.pl
chr_translate_bootstrap1.pl  chr_translate.pl             cmake_install.cmake
builder@3d3d29281e32:~/.termux-build/swi-prolog$ ls build/home/library/ | head
aggregate.pl
aggregate.qlf
ansi_term.pl
ansi_term.qlf
apply_macros.pl
apply_macros.qlf
apply.pl
apply.qlf
arithmetic.pl
arithmetic.qlf
builder@3d3d29281e32:~/.termux-build/swi-prolog$ 
```

I assume that it would not be correct to "copy and paste" any of the `.qlf` files from the "native friend" folder into the target folder, because I assume that they are binary files which are associated with corresponding libraries that are built with the differing CPU architecture and C libraries, so I assume they would not work on the target, but I have not tried that.

I noticed that inside swi-prolog, there appears to possibly be a lot of **manual parsing of UNIX-like paths written in Prolog** involved with the generation of lists of files from which to build `.qlf` files.

That makes me wonder whether maybe the problem could be related to something about the `packages` folder in the cross-compilation build folder not getting correctly detected as a folder which needs `.qlf` files generated in it, but unfortunately I struggled to understand the code any further than that.

**Comment by robertkirkman** [comment]
> If we are really ambitious we could try to support xpce. With its move to SDL+Cairo+Pango, I think it should in theory run on Android.

If you are curious to know, I think the blocker for us for that currently seems to be that we cross-compile using Ubuntu 24.04, which does not officially support SDL3, which seems to be necessary for enabling the XPCE feature in the "native friend" build to match the settings of the cross-build. It would be a little bit tedious for us to manually build a custom SDL3 inside Ubuntu as part of the steps, but if someone really wants GUI support in termux `swi-prolog`, then they could ask about it and I would know there is a demand for it. We do provide a package of SDL3 that works inside Termux, which itself doesn't require a hostbuild of SDL3 to enable in other packages that depend on SDL3.

**Comment by JanWielemaker** [comment]
So, the qlf build step succeeds silently, but does not produce the CHR .qlf files?    I'll look around a bit to see whether I can see what is wrong.

As for xpce, I propose to wait until you move to the next Ubuntu stable that should include SDL3.

**Comment by JanWielemaker** [comment]
> So, the qlf build step succeeds silently, but does not produce the CHR .qlf files? I'll look around a bit to see whether I can see what is wrong.

I do not have access to termux right now.   I wonder whether CHR is installed correctly.    Similar problems existed for the WASM version, where the .QLF compilation failed because the CHR .pl files were not correctly built and installed.   Could you check that this works?

    ?- [library(chr)].

**Comment by robertkirkman** [comment]
> > So, the qlf build step succeeds silently, but does not produce the CHR .qlf files? I'll look around a bit to see whether I can see what is wrong.
> 
> I do not have access to termux right now. I wonder whether CHR is installed correctly. Similar problems existed for the WASM version, where the .QLF compilation failed because the CHR .pl files were not correctly built and installed. Could you check that this works?
> 
> ```
> ?- [library(chr)].
> ```

Here is the output I see from that:

It appears, at least at first glance, that it is working.

```
~ $ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 9.3.30)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org

?- [library(chr)].
true.

?- 
```

> I do not have access to termux right now. 

that is OK, especially if the reason is because it is tedious to set up an Android virtual environment, that is understandable. I can try to do any tests on my devices that you would like to see the results from.

In case the reason is because you do not already have a convenient Android development environment set up, but you are curious to know what those environments are which we use to develop Termux packages and how they differ somewhat from typical Android development envrionments, these are the docker images which we use to develop and test the packages:

This Docker image is used to build our packages into special `.deb` files which work inside Termux, and this image is the environment where the problem with the QLF file generation is happening:

If desired, I could provide some reproduction commands which set up the build environment inside this container that reproduces the `chr.qlf: No such file or directory.` error, but that would only be necessary if you want to try reproducing the error in your own Docker PC, which is a really optional thing that I would completely understand if you prefer not to do.

https://hub.docker.com/r/termux/package-builder

and this other, separate docker image creates a specialized, minimal, headless Android container that has Termux preinstalled into it and carefully integrated with Docker, so this image can be used to install and test Termux packages by people who might have a Docker PC, but not necessarily any Android devices. This one has a steeper learning curve, so for people who are less familiar with Termux, a real Termux APK on a physical Android device is preferred, but this image is available as an option for people who do not have any Android devices.

https://hub.docker.com/r/termux/termux-docker

> So, the qlf build step succeeds silently, but does not produce the CHR .qlf files?

yes, I believe that is a good description of what it looks like is happening.

**Comment by JanWielemaker** [comment]
Thanks for the pointers.  So CHR seems correctly installed as .pl files.   I'm traveling and don't have the right equipment with me.   Will have a look, probably somewhere next week.

**Comment by JanWielemaker** [comment]
Nothing happened since.  There are so many updates to the build process that this should be considered stale.   Please open new issues against the current versions.

**Comment by robertkirkman** [comment]
Thanks for explaining,

I want to let you know that this issue is still reproducible, and I have been testing it regularly, but there have been no changes in the symptom.
